import Link from "next/link";

export default function HomePage() {
  return (
    <>
    <h1>AAAAAAAAAAAAAAAAAAA</h1>
    <h1>AAAAAAAAAAAAAAAAAAA</h1>
    <h1>AAAAAAAAAAAAAAAAAAA</h1>
    <h1>AAAAAAAAAAAAAAAAAAA</h1>
    <h1>AAAAAAAAAAAAAAAAAAA</h1>
    <h1>AAAAAAAAAAAAAAAAAAA</h1>
    <h1>AAAAAAAAAAAAAAAAAAA</h1>
    <h1>AAAAAAAAAAAAAAAAAAA</h1>
    <h1>AAAAAAAAAAAAAAAAAAA</h1>
    <h1>AAAAAAAAAAAAAAAAAAA</h1>
    <h1>AAAAAAAAAAAAAAAAAAA</h1>
    <h1>AAAAAAAAAAAAAAAAAAA</h1>
    <h1>AAAAAAAAAAAAAAAAAAA</h1>
    </>
  );
}
